Adds accessibility guide page
ucfopen/Materia-Docs pull request #21
Opened 2023-07-20 19:46 UTC by clpetersonucf

Adds a page to the developer section with guidelines and best practices to consider when making widgets accessible.

2023-07-20 20:27 UTC, FrenjaminBanklin requested changes
I only identified one typo, otherwise this looks great.

2023-07-20 20:27 UTC, FrenjaminBanklin commented on _developers/widget-accessibility.md
> +- **Non-sighted users** percieve the items as an unordered list when described by a screenreader. There is no non-sighted analog to dragging and dropping: rather, screenreader users make use of addit
perceive

2023-07-31 20:04 UTC, FrenjaminBanklin approved these changes
The changes look good.

2023-07-31 20:12 UTC, cayb0rg approved these changes
^^

2023-08-01 13:47 UTC, merged