Update get materia guide, heroku setup, docker setup and git urls
ucfopen/Materia-Docs pull request #7
Opened 2019-01-04 19:05 UTC by iturgeon

Now that Materia is open source, the process for getting materia has changed.  Updated the docs accordingly.

* Updated all github.com/ucfcdl links to ucfopen
* Cleaned up the Docker install instructions
* Added a page to index all the server setup options
* Added a Heroku setup page

2019-01-09 14:00 UTC, FrenjaminBanklin requested changes

2019-01-09 14:00 UTC, FrenjaminBanklin commented on _administrators/heroku.md
> +Heroku will spontaneously destroy and create new application servers as needed. Files stored on disk after building the initial image will be lost in this process. Currently, Heroku Materia v4.0.0 is
This block specified `Materia v4.0.0`. Would it make more sense to say `Materia v4.0.0 or higher`, just to specify the minimum Heroku-viable version? As is, another Materia release goes out the docs will be referring to an old version. Unless we're okay with tweaking this part of the docs with every release?

2019-01-09 14:00 UTC, FrenjaminBanklin commented on _administrators/heroku.md
> +Clicking the deploy to Heroku button below will begin building a server.  It'll install a few widgets and give you a public web address to begin playing with Materia.  The default build uses free ass
Nitpick: `the deploy to Heroku button` -> `the 'Deploy to Heroku' button`, just to match the image of the button below.

2019-01-09 14:00 UTC, FrenjaminBanklin commented on _administrators/ubuntu-apache-install-guide.md
>  2. If you're using Github 2 factor authentiaction, [create an access token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) to use as a password
Know it wasn't part of this PR, but may as well fix it while we can see it: 'authentiaction' -> 'authentication'.

2019-01-09 14:00 UTC, FrenjaminBanklin commented on get_materia.md
> +Materia is open source, so the server and many of the widgets can be found on [Github](https://github.com/ucfopen/Materia)
Needs a period at the end.

2019-01-09 14:00 UTC, FrenjaminBanklin commented on _developers/style-guide.md
> +For detailed information see our [Github PHPCS rules for Materia and FuelPHP](https://github.com/ucfopen/fuelphp-phpcs)
Needs a period at the end.

2019-01-14 22:44 UTC, iturgeon commented on _administrators/heroku.md
> +Heroku will spontaneously destroy and create new application servers as needed. Files stored on disk after building the initial image will be lost in this process. Currently, Heroku Materia v4.0.0 is
I'll just leave the v4.0.0 bit out it made sense when I was writing (I think to get at exactly what you were suggesting).  But reading it without the version seems totally fine.

2019-01-14 22:45 UTC, iturgeon commented on _administrators/heroku.md
> +Clicking the deploy to Heroku button below will begin building a server.  It'll install a few widgets and give you a public web address to begin playing with Materia.  The default build uses free ass
Agree, fought with that idea myself.

2019-01-14 22:47 UTC, iturgeon commented on _administrators/ubuntu-apache-install-guide.md
>  2. If you're using Github 2 factor authentiaction, [create an access token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) to use as a password
Looks like that whole section is irrelevant now that it's open source.

2019-01-18 19:48 UTC, FrenjaminBanklin approved these changes
One missing period I didn't notice before and one 'then' to 'than', otherwise looks fine to me.

2019-01-18 19:48 UTC, FrenjaminBanklin commented on _administrators/server-docker-development.md
> +The [Materia Docker README](https://github.com/ucfopen/Materia/blob/master/docker/README.md) will get you up and running in less then 10 minutes.
'than'

2019-01-18 19:48 UTC, FrenjaminBanklin commented on _administrators/heroku.md
> +To run any of the [administration commands]({{ site.baseurl }}/admin/administrative-commands.html) on your Heroku server, access the Run Console menu item from your Heroku Dashboard
Needs a period at the end. Missed this one before.

2019-01-29 01:15 UTC, merged